name: Update Wrestling Data

on:
  schedule:
    # Run daily at 6 AM EST (11 AM UTC)
    - cron: '0 11 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: |
        python scraper_selenium_final.py
        
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code data/wrestling_data.json || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/wrestling_data.json
        git commit -m "Update wrestling data - $(date +'%Y-%m-%d %H:%M')"
        git pull --rebase origin main
        git push
        
    - name: No changes
      if: steps.git-check.outputs.changed != 'true'
      run: |
        echo "No changes to wrestling data"
